version: "3.7"
services:
  php:
    build:
      context: .
    image: phpdocker
    container_name: php-oo
    ports:
      - "4000:4000"
    volumes:
      - ".:/var/www/html/"
    command: php -S 0.0.0.0:4000
